# Subsets con una condicion

# En los arrays también podemos usar los operadores < y > para extraer subsets basados en un valor dado.

In [ ]:
# import numpy as np

multidimensional = np.random.randint(0, 100, (2, 3, 5))

multidimensional = array([[[18,  5, 58, 75, 20],
                           [30, 27, 13, 58, 74],
                           [36, 86, 65, 40, 33]],

                          [[43, 68, 32,  2, 60],
                           [95, 19, 10, 49,  9],
                           [64, 91, 56, 42, 52]]], dtype=int32)

In [ ]:
# Queremos extraer aquellos valores mayores a 45

multidimensional > 45

# Salida: 
"""
array([[[False, False,  True,  True, False],
        [False, False, False,  True,  True],
        [False,  True,  True, False, False]],

       [[False,  True, False, False,  True],
        [ True, False, False,  True, False],
        [ True,  True,  True, False,  True]]])
"""
# Devuelve un array de boleanos que cumplen la condición

array([[[False, False,  True,  True, False],
        [False, False, False,  True,  True],
        [False,  True,  True, False, False]],

       [[False,  True, False, False,  True],
        [ True, False, False,  True, False],
        [ True,  True,  True, False,  True]]])

In [ ]:
# Para obtener un array unidimensional con los valores que cumplen la condición:

multidimensional[multidimensional > 45]  
# Salida: array([58, 75, 58, 74, 86, 65, 68, 60, 95, 49, 64, 91, 56, 52], dtype=int32)

array([58, 75, 58, 74, 86, 65, 68, 60, 95, 49, 64, 91, 56, 52],
      dtype=int32)

# Subsets con múltiples condiciones

# En la librería Numpy los operadores AND y OR se escriben de otra forma:

OR --> |
AND --> &

In [ ]:
multidimensional = array([[[18,  5, 58, 75, 20],
                           [30, 27, 13, 58, 74],
                           [36, 86, 65, 40, 33]],

                          [[43, 68, 32,  2, 60],
                           [95, 19, 10, 49,  9],
                           [64, 91, 56, 42, 52]]], dtype=int32)

In [ ]:
# Queremos seleccionar aquellos números que sean MAYORES que 60 o MENORES que 15

multidimensional[(multidimensional > 60) | (multidimensional < 15)]
# Salida: array([ 5, 75, 13, 74, 86, 65, 68,  2, 95, 10,  9, 64, 91], dtype=int32)

array([ 5, 75, 13, 74, 86, 65, 68,  2, 95, 10,  9, 64, 91], dtype=int32)

In [ ]:
# Queremos seleccionar aquellos números que sean MAYORES que 45 e IGUAL a 58

multidimensional[(multidimensional > 45) & (multidimensional == 58)]
# Salida: array([58, 58], dtype=int32)

array([58, 58], dtype=int32)