# Operaciones array - escalar (número)

# Este tipo de acciones corresponden a operaciones entre un array y un número.

In [3]:
import numpy as np

In [4]:
mi_array = np.array([[1, 2, 3], [3, 4, 5]])

mi_array  # Salida: array([[1, 2, 3],
          #                [3, 4, 5]])

array([[1, 2, 3],
       [3, 4, 5]])

In [ ]:
# Sumar:
print(mi_array + 4)  # Salida: [[5 6 7]
                     #          [7 8 9]]

# Restar:
print(mi_array - 2)  # Salida: [[-1  0  1]
                     #          [ 1  2  3]]

# Multiplicar:
print(mi_array * 2)  # Salida: [[ 2  4  6]
                     #          [ 6  8 10]]

# Dividir: 
print(mi_array / 3)  # Salida: [[0.33333333 0.66666667 1.        ]
                     #          [1.         1.33333333 1.66666667]]

# Módulo:
print(mi_array % 3)  # Salida: [[1 2 0]
                     #          [0 1 2]]

# División entera:
print(mi_array // 3)  # Salida: [[0 0 1]
                     #          [1 1 1]]

# Potencia:
print(mi_array ** 3)  # Salida: [[  1   8  27]
                     #          [ 27  64 125]]

[[5 6 7]
 [7 8 9]]
[[-1  0  1]
 [ 1  2  3]]
[[ 2  4  6]
 [ 6  8 10]]
[[0.33333333 0.66666667 1.        ]
 [1.         1.33333333 1.66666667]]
[[1 2 0]
 [0 1 2]]
[[0 0 1]
 [1 1 1]]
[[  1   8  27]
 [ 27  64 125]]


# Operaciones entre arrays

# Es imprescindible que tengan la misma dimensión.

In [ ]:
# Creamos nuestra primera array:
array_1 = np.ones((2, 3, 4))

array_1 = [[[1., 1., 1., 1.],
            [1., 1., 1., 1.],
            [1., 1., 1., 1.]],

           [[1., 1., 1., 1.],
            [1., 1., 1., 1.],
            [1., 1., 1., 1.]]]

In [ ]:
# Creamos nuestra segunda array:
array_2 = np.random.randint(0, 10, (2, 3, 4))

array_2 = [[[9, 0, 0, 2],
            [8, 1, 3, 6],
            [9, 0, 0, 8]],

           [[7, 2, 3, 0],
            [9, 3, 5, 2],
            [7, 6, 4, 0]]]

In [ ]:
# Sumar, dos formas de hacerlo:

# array_1 + array_2 

suma = np.add(array_1, array_2)    

suma  # Salida: array([[[10.,  1.,  1.,  3.],
      #                 [ 9.,  2.,  4.,  7.],
      #                 [10.,  1.,  1.,  9.]],

      #                [[ 8.,  3.,  4.,  1.],
      #                 [10.,  4.,  6.,  3.],
      #                 [ 8.,  7.,  5.,  1.]]])

In [ ]:
# .astype(): método para cambiar el tipo de los datos de nuestro array:

suma = suma.astype(int)

suma  # Salida: array([[[10,  1,  1,  3],
      #                 [ 9,  2,  4,  7],
      #                 [10,  1,  1,  9]],

      #                [[ 8,  3,  4,  1],
      #                 [10,  4,  6,  3],
      #                 [ 8,  7,  5,  1]]])  


In [ ]:
# Restar, dos formas de hacerlo:

# array_1 - array_2 

resta = np.subtract(array_1, array_2)

resta  # Salida: array([[[-8.,  1.,  1., -1.],
       #                 [-7.,  0., -2., -5.],
       #                 [-8.,  1.,  1., -7.]],

       #                [[-6., -1., -2.,  1.],
       #                 [-8., -2., -4., -1.],
       #                 [-6., -5., -3.,  1.]]])

In [ ]:
# Multiplicar, dos formas de hacerlo:

# array_1 * array_2 

multiplicacion = np.multiply(array_1, array_2)

multiplicacion  # Salida: array([[[9., 0., 0., 2.],
                #                 [8., 1., 3., 6.],
                #                 [9., 0., 0., 8.]],

                #                [[7., 2., 3., 0.],
                #                 [9., 3., 5., 2.],
                #                 [7., 6., 4., 0.]]])

In [ ]:
# Dividir, dos formas de hacerlo:

# array_1 / array_2 

division = np.divide(array_1, array_2)

division  # Salida: array([[[0.11111111,        inf,        inf, 0.5       ],
          #                 [0.125     , 1.        , 0.33333333, 0.16666667],
          #                 [0.11111111,        inf,        inf, 0.125     ]],

          #                [[0.14285714, 0.5       , 0.33333333,        inf],
          #                 [0.11111111, 0.33333333, 0.2       , 0.5       ],
          #                 [0.14285714, 0.16666667, 0.25      ,        inf]]])

# El valor inf (infinito) aparece en aquellos lugares donde se está dividiendo por cero, es decir, 
# cuando algún elemento correspondiente de array_2 es 0.

In [ ]:
# División entera:

division_entera = array_1 // array_2

division_entera  # Salida: array([[[ 0., inf, inf,  0.],
                 #                 [ 0.,  1.,  0.,  0.],
                 #                 [ 0., inf, inf,  0.]],

                 #                [[ 0.,  0.,  0., inf],
                 #                 [ 0.,  0.,  0.,  0.],
                 #                 [ 0.,  0.,  0., inf]]])