# Operaciones estadísticas

# Todos los métodos que se van a utiizar permiten operar con los ejes, pasándole el parámetro axis, donde:

# axis = 0: nos calculará el operador que indiquemos para cada columna de nuestro array.

# axis = 1: nos calculará el operador que indiquemos para cada fila de nuestro array.

In [3]:
import numpy as np

In [26]:
array = np.random.randint(1, 20, (4, 5))

array = np.array([[ 2,  3, 16,  2, 15],
         [16,  4,  9,  1,  2],
         [ 7,  7, 13,  6, 12],
         [ 1,  5, 14, 13, 15]])

# np.mean()

# Calcular la media de elementos de un array

In [ ]:
# Calcular la media de todos los elementos del array, si no indicamos el parámetro "axis".
media = np.mean(array)

media  # Salida: 8.15 

np.float64(8.15)

In [ ]:
# Media por columnas, nos devuelve un valor por cada columna de nuestro array:
media_columnas = np.mean(array, axis = 0)

media_columnas  # Salida: array([ 6.5 ,  4.75, 13.  ,  5.5 , 11.  ])

array([ 6.5 ,  4.75, 13.  ,  5.5 , 11.  ])

In [ ]:
# Media por filas, nos devuelve un valor por cada fila de nuestro array:
media_filas = np.mean(array, axis = 1)

media_filas  # Salida: array([7.6, 6.4, 9. , 9.6])

array([7.6, 6.4, 9. , 9.6])

# np.std()

# Calcula la desviación estándar del array

In [ ]:
# Calcular la desviación estandar de todos los elementos del array, si no indicamos el parámetro "axis".
desviacion_std = np.std(array)

desviacion_std  # Salida: 5.433921236087252

np.float64(5.433921236087252)

In [ ]:
# Desviación estándar por columnas, nos devuelve un valor por cada columna de nuestro array:
desviacion_std_columnas = np.std(array, axis = 0)

desviacion_std_columnas  # Salida: array([5.93717104, 1.47901995, 2.54950976, 4.71699057, 5.33853913])

array([5.93717104, 1.47901995, 2.54950976, 4.71699057, 5.33853913])

In [ ]:
# Desviación estándar por filas, nos devuelve un valor por cada columna de nuestro array:
desviacion_std_filas = np.std(array, axis = 1)

desviacion_std_filas  # Salida: array([6.46838465, 5.535341  , 2.89827535, 5.57135531])

array([6.46838465, 5.535341  , 2.89827535, 5.57135531])

# np.var()

# Calcula la varianza del array

In [27]:
# Calcular la varianza de todos los elementos del array, si no indicamos el parámetro "axis".
varianza = np.var(array)

varianza  # Salida: 29.527500000000003

np.float64(29.527500000000003)

In [28]:
# Varianza por columnas, nos devuelve un valor por cada columna de nuestro array:
varianza_columnas = np.var(array, axis = 0)

varianza_columnas  # Salida: array([35.25  ,  2.1875,  6.5   , 22.25  , 28.5   ])

array([35.25  ,  2.1875,  6.5   , 22.25  , 28.5   ])

In [ ]:
# Varianza por filas, nos devuelve un valor por cada columna de nuestro array:
varianza_filas = np.var(array, axis = 1)

varianza_filas  # Salida: array([41.84, 30.64,  8.4 , 31.04])

array([41.84, 30.64,  8.4 , 31.04])

# Operaciones aritméticas

In [29]:
array = np.array([[ 2,  3, 16,  2, 15],
         [16,  4,  9,  1,  2],
         [ 7,  7, 13,  6, 12],
         [ 1,  5, 14, 13, 15]])

# np.min()

# Nos devuelve el valor mínimo contenido dentro del array 

In [ ]:
# Calcular el valor mínimo de todos los elementos del array, si no indicamos el parámetro "axis".
minimo = np.min(array)

minimo  # Salida: 1

np.int64(1)

In [ ]:
# Valor mínimo por columnas, nos devuelve un valor por cada columna de nuestro array:
minimo_columnas = np.min(array, axis = 0)

minimo_columnas  # Salida: array([1, 3, 9, 1, 2])

array([1, 3, 9, 1, 2])

In [ ]:
# Valor mínimo por filas, nos devuelve un valor por cada columna de nuestro array:
minimo_filas = np.min(array, axis = 1)

minimo_filas  # Salida: array([2, 1, 6, 1])

array([2, 1, 6, 1])

# np.max()

# Nos devuelve el valor máximo contenido dentro del array 

In [ ]:
# Calcular el valor máximo de todos los elementos del array, si no indicamos el parámetro "axis".
maximo = np.max(array)

maximo  # Salida: 16

np.int64(16)

In [ ]:
# Valor máximo por columnas, nos devuelve un valor por cada columna de nuestro array:
maximo_columnas = np.max(array, axis = 0)

maximo_columnas  # Salida: array([16,  7, 16, 13, 15])

array([16,  7, 16, 13, 15])

In [ ]:
# Valor máximo por filas, nos devuelve un valor por cada columna de nuestro array:
maximo_filas = np.max(array, axis = 1)

maximo_filas  # Salida: array([16, 16, 13, 15])

array([16, 16, 13, 15])

# np.sum()

# Nos devuelve la suma del contenido dentro del array 

In [ ]:
# Calcular la suma de todos los elementos del array, si no indicamos el parámetro "axis".
suma = np.sum(array)

suma  # Salida: 163

np.int64(163)

In [13]:
# Calcular la suma por columnas, nos devuelve un valor por cada columna de nuestro array:
suma_columnas = np.sum(array, axis = 0)

suma_columnas  # Salida: array([16,  7, 16, 13, 15])

array([26, 19, 52, 22, 44])

In [ ]:
# Calcular la suma por filas, nos devuelve un valor por cada columna de nuestro array:
suma_filas = np.sum(array, axis = 1)

suma_filas  # Salida: array([38, 32, 45, 48])

array([38, 32, 45, 48])

# np.cumsum()

# Nos devuelve la suma acumulada del contenido dentro del array

# La suma acumulativa es una operación matemática que consiste en ir sumando los elementos de una secuencia uno a uno, acumulando el total en cada paso.

In [ ]:
# Calcular la suma acumulada de todos los elementos del array, si no indicamos el parámetro "axis".
suma_acumulada = np.cumsum(array)

suma_acumulada  # Salida: array([  2,   5,  21,  23,  38,  54,  58,  67,  68,  70,  77,  84,  97, 103, 115, 116, 121, 135, 148, 163])

In [ ]:
# Calcular la suma acumulada por columnas:
suma_acumulada_columnas = np.cumsum(array, axis = 0)

suma_acumulada_columnas  # Salida: array([[ 2,  3, 16,  2, 15],
                         #                [18,  7, 25,  3, 17],
                         #                [25, 14, 38,  9, 29],
                         #                [26, 19, 52, 22, 44]])

In [ ]:
# Calcular la suma acumulada por filas:
suma_acumulada_filas = np.cumsum(array, axis = 1)

suma_acumulada_filas  # Salida: array([[ 2,  5, 21, 23, 38],
                      #                [16, 20, 29, 30, 32],
                      #                [ 7, 14, 27, 33, 45],
                      #                [ 1,  6, 20, 33, 48]])

# np.cumprod()

# Nos devuelve un array con el producto acumulado de todos los elementos del array

In [ ]:
# Calcular el producto acumulado de todos los elementos del array, si no indicamos el parámetro "axis".
producto_acumulado = np.cumprod(array)

producto_acumulado  # Salida: array([               2,                6,               96,
                    #                             192,             2880,            46080,
                    #                          184320,          1658880,          1658880,
                    #                         3317760,         23224320,        162570240,
                    #                      2113413120,      12680478720,     152165744640,
                    #                    152165744640,     760828723200,   10651602124800,
                    #                 138470827622400, 2077062414336000])

In [ ]:
# Calcular el producto acumulado por columnas:
producto_acumulado_columnas = np.cumprod(array, axis = 0)

producto_acumulado_columnas  # Salida: array([[    2,     3,    16,     2,    15],
                             #                [   32,    12,   144,     2,    30],,
                             #                [  224,    84,  1872,    12,   360],
                             #                [  224,   420, 26208,   156,  5400]])

In [ ]:
# Calcular el producto acumulado por filas:
producto_acumulado_filas = np.cumprod(array, axis = 1)

producto_acumulado_filas  # Salida: array([[    2,     6,    96,   192,  2880],
                          #                [   16,    64,   576,   576,  1152],
                          #                [    7,    49,   637,  3822, 45864],
                          #                [    1,     5,    70,   910, 13650]])

# np.sqrt()

# Calcula la raíz cuadrada no negativa para cada elemento de nuestro array

In [ ]:
# Calcular la raíz cuadrada no negativa de todos los elementos del array.
raiz_cuadrada = np.sqrt(array)

raiz_cuadrada  # Salida: array([[1.41421356, 1.73205081, 4.        , 1.41421356, 3.87298335],
               #                [4.        , 2.        , 3.        , 1.        , 1.41421356],
               #                [2.64575131, 2.64575131, 3.60555128, 2.44948974, 3.46410162],
               #                [1.        , 2.23606798, 3.74165739, 3.60555128, 3.87298335]])

# np.exp()

# Calcula el exponencial de cada elemento de nuestro array.

# Devuelve: un array del mismo tipo con el resultado de aplicar e ** x a cada elemento, exponencial elevado a cada elemento.

# e = número de Euler, aproximadamente 2.71828

In [ ]:
# Calcular el exponencial de todos los elementos del array.
exponencial = np.exp(array)

exponencial  # Salida: array([[7.38905610e+00, 2.00855369e+01, 8.88611052e+06, 7.38905610e+00, 3.26901737e+06],
             #                [8.88611052e+06, 5.45981500e+01, 8.10308393e+03, 2.71828183e+00, 7.38905610e+00],
             #                [1.09663316e+03, 1.09663316e+03, 4.42413392e+05, 4.03428793e+02, 1.62754791e+05],
             #                [2.71828183e+00, 1.48413159e+02, 1.20260428e+06, 4.42413392e+05, 3.26901737e+06]])

# Operaciones de comparación

# np.any()

# Comprueba si algún elemento del array se evalúa como True dada una condición. Si en alguno de los elementos de nuestro array se cumple la condición nos devolverá un True

In [ ]:
array = np.array([[ 2,  3, 16,  2, 15],
                  [16,  4,  9,  1,  2],
                  [ 7,  7, 13,  6, 12],
                  [ 1,  5, 14, 13, 15]])

In [ ]:
# Comparar la condición en todos los elementos del array, si no indicamos el parámetro "axis".
print(np.any(array > 10))  # Salida: True

print(np.any(array) > 20)  # Salida: False

True
False


In [ ]:
# Comparar la condición en todos los elementos del array por columnas:
print(np.any(array > 10, axis = 0)) # Salida: [ True False  True  True  True]

print(np.any(array < 2, axis = 0))  # Salida: [ True False False  True False]

[ True False  True  True  True]
[ True False False  True False]


In [ ]:
# Comparar la condición en todos los elementos del array por filas:
print(np.any(array > 15, axis = 1)) # Salida: [ True  True False False]

print(np.any(array < 2, axis = 1))  # Salida: [False  True False  True]

[ True  True False False]
[False  True False  True]


# np.all()

# Comprueba si todos los elementos del array cumplen la condición que le pasamos. Si todos la cumplen devuelve True

In [ ]:
# Comparar la condición en todos los elementos del array, si no indicamos el parámetro "axis".
print(np.all(array > 10))  # Salida: False

print(np.any(array) >= 1)  # Salida: True

False
True


In [49]:
# Comparar la condición en todos los elementos del array por columnas:
print(np.all(array < 10, axis = 0)) # Salida: [False  True False False False]

print(np.all(array > 2, axis = 0))  # Salida: [False  True  True False False]

[False  True False False False]
[False  True  True False False]


In [ ]:
# Comparar la condición en todos los elementos del array por filas:
print(np.all(array < 15, axis = 1)) # Salida: [False False  True False]

print(np.all(array > 2, axis = 1))  # Salida: [False False  True False]

[False False  True False]
[False False  True False]
