# Métodos de los arrays

# np.copy()

# Nos devuelve una copia del array que le pasamos 

# Si modificamos la copia no afecta a la original

In [1]:
import numpy as np

In [ ]:
array = np.random.randint(0,20, (2, 3))

array  # Salida: array([[ 9, 11,  3],
       #                [10, 14, 12]], dtype=int32)

array([[ 9, 11,  3],
       [10, 14, 12]], dtype=int32)

In [ ]:
# Hacer una copia de array:
array_copia = array.copy()  # Es lo mismo:  array_copia = np.copy(array)

array_copia  # Salida: array([[ 9, 11,  3],
             #                [10, 14, 12]], dtype=int32)

array([[ 9, 11,  3],
       [10, 14, 12]], dtype=int32)

In [ ]:
# Modificar la copia
array_copia[0, 1] = 20

array_copia  # Salida: array([[ 9, 20,  3],
             #                [10, 14, 12]], dtype=int32) 

array([[ 9, 20,  3],
       [10, 14, 12]], dtype=int32)

In [ ]:
# Comprobar que no se ha modificado la original

array  # Salida: array([[ 9, 11,  3],
       #                [10, 14, 12]], dtype=int32) 

array([[ 9, 11,  3],
       [10, 14, 12]], dtype=int32)

# np.transpose() 

# Invierte los ejes de una matriz; devuelve la matriz modificada sin modificar la original.

In [ ]:
# Unidimensional, en estas arrays no hace nada, es decir, nos devuelve la misma array
# Crear array:
unidimensional = np.arange(10, 20)

unidimensional  # Salida: array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
# Aplicar el método:
np.transpose(unidimensional)  # Salida: array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
# Bidimensional, las filas pasan a ser columnas y las columnas pasa a ser las filas.
# Crear array:
bidimensional = np.random.randint(0,20, (2,3))

bidimensional  # Salida: array([[ 6,  0, 18],
               #                [10,  0, 12]], dtype=int32)

array([[ 6,  0, 18],
       [10,  0, 12]], dtype=int32)

In [ ]:
# Aplicar el método:
np.transpose(bidimensional)  # Salida: array([[ 6, 10],
                             #                [ 0,  0],
                             #                [18, 12]], dtype=int32)

array([[ 6, 10],
       [ 0,  0],
       [18, 12]], dtype=int32)

In [ ]:
# multidimensional, por defecto el número de matrices pasa a ser el número de columnas y viceversa.
# Crear array:
multidimensional = np.random.randint(0,30, (2,3,5))

multidimensional  # Salida: array([[[14, 18,  8, 26, 19],
                #                 [17,  8, 15,  9,  1],
                #                 [15, 28,  5, 14, 16]],

                #                [[ 2, 28, 16, 15, 23],
                #                 [21, 26,  7, 14, 16],
                #                 [ 8, 22, 29, 25, 21]]], dtype=int32)

In [ ]:
# Aplicar método, la estructura del array pasa a ser (5, 3, 2)
np.transpose(multidimensional)  # Salida: array([[[14,  2],
                              #                 [17, 21],
                              #                 [15,  8]],

                              #                 [[18, 28],
                              #                  [ 8, 26],
                              #                  [28, 22]],

                              #                 [[ 8, 16],
                              #                  [15,  7],
                              #                  [ 5, 29]],

                              #                 [[26, 15],
                              #                  [ 9, 14],
                              #                  [14, 25]],

                              #                 [[19, 23],
                              #                  [ 1, 16],
                              #                  [16, 21]]], dtype=int32)

In [ ]:
# Podemos especificar el sentido en el que queremos que se transpongan los elementos de nuestro array.

np.transpose(multidimensional, (1, 2, 0)) # Donde: 0 = nº matrices; 1 = Filas; 2 = columnas

# La estructura original de la matriz multidimensional es: (2, 3, 5)
# Al aplicar el método e indicarle (1, 2, 0), la estructura pasa a ser: (3, 5, 2)

# Salida: array([[[14,  2],
#                 [18, 28],
#                 [ 8, 16],
#                 [26, 15],
#                 [19, 23]],

#                [[17, 21],
#                 [ 8, 26],
#                 [15,  7],
#                 [ 9, 14],
#                 [ 1, 16]],

#                [[15,  8],
#                 [28, 22],
#                 [ 5, 29],
#                 [14, 25],
#                 [16, 21]]])

# np.reshape()

# Invierte los ejes de una matriz; devuelve la matriz modificada sin modificar la original. 

# Modifica la forma de la matriz, pero el número total de elementos debe coincidir siempre

In [ ]:
# Crear un array unidimensional de 12 elementos:
array2 = np.arange(12)

array2  # Salida: array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# Cambiar la forma a (4, 3), el número total de elementos debe coincidir siempre

np.reshape(array2, (4, 3))  # Salida: array([[ 0,  1,  2],
                            #                [ 3,  4,  5],
                            #                [ 6,  7,  8],
                            #                [ 9, 10, 11]])

In [ ]:
# Cambiar la forma a (3, 4), el número total de elementos debe coincidir siempre

np.reshape(array2, (3, 4))  # Salida: array([[ 0,  1,  2,  3],
                            #                [ 4,  5,  6,  7],
                            #                [ 8,  9, 10, 11]])

In [ ]:
# Cambiar la forma a (2, 2, 3), el número total de elementos debe coincidir siempre

np.reshape(array2, (2, 2, 3))  # Salida: array([[[ 0,  1,  2],
                               #                 [ 3,  4,  5]],

                               #                [[ 6,  7,  8],
                               #                 [ 9, 10, 11]]])

In [ ]:
# Definir la forma de un nuevo array combinando los métodos: .arange y .reshape
nueva_forma = np.arange(16).reshape(2, 2, 4)

nueva_forma  # Salida: array([[[ 0,  1,  2,  3],
             #                 [ 4,  5,  6,  7]],

             #                [[ 8,  9, 10, 11],
             #                 [12, 13, 14, 15]]])

# np.swapaxes()

# Intercambia dos ejes de una matriz.

In [ ]:
# Crear nueva array:
array3 = np.arange(1,7).reshape(2, 3)

array3  # Salida: array([[1, 2, 3],
        #                [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Aplicar el método, donde 0 = Filas; 1 = columnas 

np.swapaxes(array3, 1, 0)  # Salida: array([[1, 4],
                           #                [2, 5],
                           #                [3, 6]])

array([[1, 4],
       [2, 5],
       [3, 6]])

# Se puede utilizar en multidimensionales también, donde: 0 = nº matrices; 1 = Filas; 2 = columnas