# Funciones de vectores

In [1]:
import numpy as np

# Métodos que podemos utilizar en arrays.

# Solamente el primer método (np.unique) es aplicable a los distintos tipos de array. Los demás son para arrays unidimensionales.

# np.unique()

# Encuentra los valores únicos del array que le pasemos. Únicos solo los muestra una vez, tanto como si están repetidos como si no.

# Devuelve un array unidimensional ordenado con los valores únicos, discriminando las repeticiones.

# Usando el parámetro return_index podemos saber en cuál posición del array principal se encuentran, lo devuelve en forma de array, el primer elemento de esa array corresponde a la posición del primer elemento en el array principal.

# Usando el parámetro return_count podemos saber la cantidad de veces que está un elemento en el array principal, lo devuelve en forma de array.

In [ ]:
# Crear un array (2, 3, 4)
array = np.random.randint(1,21, (2, 3, 4))

array  # Salida: array([[[15, 16, 20, 16],
       #                 [ 1,  1,  8,  5],
       #                 [ 5, 14, 14,  4]],

       #                [[12, 15, 12, 10],
       #                 [ 3,  9, 12,  7],
       #                 [ 8,  4, 16,  1]]]

In [ ]:
# Array de valores únicos:

np.unique(array)  # Salida: array([ 1,  3,  4,  5,  7,  8,  9, 10, 12, 14, 15, 16, 20]

In [ ]:
# Posición de los valores únicos

np.unique(array, return_index = True)  # Salida: (array([ 1,  3,  4,  5,  7,  8,  9, 10, 12, 14, 15, 16, 20], 
                                       #          array([ 4, 16, 11,  7, 19,  6, 17, 15, 12,  9,  0,  1,  2]))

# El elemento con valor 1 se encuentra por primera vez en el array principal en la posición 4.
# El elemento con valor 15 se encuentra por primera vez en el array principal en la posición 0.
# El elemeto con valor 20 no está repetido en toda el array y se encuentra en la posición 2,

In [ ]:
# Contar la veces que se encuentra un elemento en el array principal:

np.unique(array, return_counts = True)  # Salida: (array([ 1,  3,  4,  5,  7,  8,  9, 10, 12, 14, 15, 16, 20], 
                                        #          array([3, 1, 2, 2, 1, 2, 1, 1, 3, 2, 2, 3, 1]))

# El elemento con valor 1 se encuentra 3 veces en el array principal.
# El elemento con valor 20 se encuentra 1 vez en el array principal.                                      

# np.intersect1d() 

# Encuentra la intersección entre dos arrays, es decir, los elementos que son comunes en los dos. Nos devuelve un array con los valores únicos de la intersección y ordenados que se encuentran en ambos.

# Usando el parámetro return_indices podemos saber en qué posición están los elementos de la intersección. 

In [7]:
# Creamos dos arrays:

arr1 = np.array([4,5,6,8])
arr2 = np.array([4,9,1,5])

In [ ]:
# Array intersección:

np.intersect1d(arr1, arr2)  # Salida: array([4, 5])

In [ ]:
# Array con las posiciones de los valores del array intersección:

np.intersect1d(arr1, arr2, return_indices = True)  # Salida: (array([4, 5]), array([0, 1]), array([0, 3]))

# En el resultado, 1º array valores intersección, 2º array posiciones de valores intersección en arr1, 3º array posiciones de valores intersección en arr2
# El elemento con valor 4 se encuentra en la posición 0 de arr1
# El elemento con valor 5 se encuentra en la posición 1 de arr1 
# El elemento con valor 4 se encuentra en la posición 0 de arr2
# El elemento con valor 5 se encuentra en la posición 3 de arr2 

# np.union1d() 

# Devuelve un array ordenado con los elementos resultantes de unir los arrays sin tener encuenta las repeticiones.

In [ ]:
# Unir dos arrays:

np.union1d(arr1, arr2)  # Salida: array([1, 4, 5, 6, 8, 9])

# np.in1d() --> Actualmente se utiliza np.isin()

# Devuelve un array de booleanos con información sobre qué elementos del array "A" se encuentran también en el array "B"

In [ ]:
# Recordamos nuestras arrays:
arr1 = np.array([4,5,6,8])
arr2 = np.array([4,9,1,5])

In [ ]:
# Comparar arr1 con arr2:
np.in1d(arr1, arr2)  # Salida: array([ True,  True, False, False])  -->  4 y 5 se encuentran en arr2, 6 y 8 no se encuentran en arr2

In [ ]:
# El orden es importante en la comparación:

np.isin(arr2, arr1)  # Salida: array([ True, False, False,  True])

# np.setdiff1d()

# Devuelve un array ordenado con los valores únicos que están en el array "A" pero no en el "B".

In [ ]:
# Comparar arr1 con arr2:

np.setdiff1d(arr1, arr2)  # Salida: array([6, 8])  -->  6 y 8 están en arr1 pero no en arr2

In [ ]:
# El orden es importante en la comparación:

np.setdiff1d(arr2, arr1)  # Salida: array([1, 9])

# np.setxor1d()

# Devuelve un array ordenado con los valores únicos del conjunto de elementos que pertenecen a "A" o "B", pero no a ambos. Es decir, nos va a devolver los elementos únicos que solo encontremos en cada uno de los arrays cuando los comparamos.

# Es el método inverso de np.intersect1d()

In [ ]:
# Recordamos nuestras arrays:
arr1 = np.array([4,5,6,8])
arr2 = np.array([4,9,1,5])

In [ ]:
# Array con valores no repetidos entre arrays

np.setxor1d(arr1, arr2)  # Salida: array([1, 6, 8, 9])  

array([1, 6, 8, 9])