# Numpy

# NumPy (acrónimo de Numerical Python) es una librería especializada en el cálculo numérico y el análisis de datos, especialmente para un gran volumen de datos.

# Incorpora una nueva clase de objetos llamados arrays que permite representar colecciones de datos de un mismo tipo en varias dimensiones, y funciones muy eficientes para su manipulación.

# Tipos:
    - Unidimensionales o 1D array:  se puede imaginar como si se tratase de una lista de datos.
    - Bidimensionales o 2D array: se pueden definir como matrices que se pueden representar como una colección de datos         almacenados en filas y columnas.
    - Multidimensional o 3D array: el número de índices viene determinado por el número de dimensiones de nuestro array, por ejemplo, para un array tridimensional el número de índice sería 3.



# Instalación e importación

In [ ]:
# pip install numpy
# import numpy as np
# print(np.__version__)

# pip install pandas
# import pandas as pd
# print(pd.__version__)

# Creación de arrays

In [ ]:
# np.array(): crear un array a partir de un iterable como una lista.

lista = [2, 3, 5]
array1 = np.array(lista)

print(array1)  #  Salida: [2 3 5]

array1  #  Salida: array([2, 3, 5])


[2 3 5]


array([2, 3, 5])

In [ ]:
# Crear array bidimensional a partir de una lista de listas.

lista2 = [[1,2,3], [4,5,6]]
array2 = np.array(lista2)

print(array2)  # Salida: [[1 2 3]
               #          [4 5 6]]
               
array2  # Salida: array([[1, 2, 3],
        #               [4, 5, 6]])

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Crear array tridimensional a partir de una lista de listas de listas.

lista3 = [[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]]
array3 = np.array(lista3)

array3  # Salida: array([[[ 1,  2,  3],
        #                 [ 4,  5,  6]],

        #                [[ 7,  8,  9],
        #                 [10, 11, 12]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
# np.arange(): Nos permite crear arrays con valores uniformes dentro de un intervalo determinado.

# crear array unidimensional con números del 1 al 9

array4 = np.arange(1, 10)

array4  # Salida: array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Crear array unidimensional con números del 1 al 9 con saltos de dos en dos

array5 = np.arange(1, 10, 2)

array5  # Salida: array([1, 3, 5, 7, 9])


array([1, 3, 5, 7, 9])

In [ ]:
# np.zeros(): Nos permite crear arrays de un tamaño especificado inicializados con ceros.

# Crear array unidimensional de ceros.

ceros1 = np.zeros(3, dtype= float)  # Tres elementos de tipo float. Si no se indica dtype=, por defecto es float 

ceros1  # Salida: array([0., 0., 0.])


array([0., 0., 0.])

In [ ]:
# Crear arrays bidimensional de ceros, de tipo enteros.

ceros2 = np.zeros((2, 3), dtype= int)  # 2 Indica número de filas, el 3 las columnas.

ceros2  # Salida: array([[0, 0, 0],
        #                [0, 0, 0]])

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
# Crear arrays tridimensional de ceros. 2 matrices de 3 filas x 5 columnas.

ceros3 = np.zeros((2, 3, 5), dtype= int) # 2 indica número de matrices, 3 indica número de filas, el 5 las columnas.

ceros3  # Salida: array([[[0, 0, 0, 0, 0],
        #                 [0, 0, 0, 0, 0],
        #                 [0, 0, 0, 0, 0]],

        #                [[0, 0, 0, 0, 0],
        #                 [0, 0, 0, 0, 0],
        #                 [0, 0, 0, 0, 0]]])

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [ ]:
# np.ones(): Nos permite crear arrays de un tamaño especificado inicializados con unos.

# Crear array unidimensional de unos.

unos1 = np.ones(5)  # Si no indicamos el tipo devuelve float 

unos1  # Salida: array([1., 1., 1., 1., 1.])

array([1., 1., 1., 1., 1.])

In [ ]:
# Crear array bidimensional de unos, 2 filas x 3 columnas, float por defecto.

unos2 = np.ones((2, 3))

unos2  # Salida: array([[1., 1., 1.],
       #                [1., 1., 1.]])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Crear array tridimensional de unos (enteros). 2 matrices de 3 filas x 6 columnas 

unos3 = np.ones((2, 3, 6), dtype= int)

unos3  # Salida: array([[[1, 1, 1, 1, 1, 1],
       #                 [1, 1, 1, 1, 1, 1],
       #                 [1, 1, 1, 1, 1, 1]],

       #                [[1, 1, 1, 1, 1, 1],
       #                 [1, 1, 1, 1, 1, 1],
       #                 [1, 1, 1, 1, 1, 1]]])


array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]])

In [51]:
# np.empty(): Nos permite crear "arrays vacíos" con las dimensiones especificadas.
 
# Los valores que se generan en este array son los que estén almacenados en ese momento en la memoria, lo que podría parecer aleatoriedad.

vacio1 = np.empty((4,3))

vacio1 # Salida: array([[1.24461877e-311, 1.24461877e-311, 1.24461877e-311],
       #                [1.26974871e-321, 0.00000000e+000, 1.65814725e-076],
       #                [9.27279402e-072, 5.28882111e+174, 2.48481943e+184],
       #                [4.12352210e-061, 1.32710585e-075, 8.07011090e+169]])

array([[1.24461877e-311, 1.24461877e-311, 1.24461877e-311],
       [1.26974871e-321, 0.00000000e+000, 1.65814725e-076],
       [9.27279402e-072, 5.28882111e+174, 2.48481943e+184],
       [4.12352210e-061, 1.32710585e-075, 8.07011090e+169]])

In [ ]:
# np.identity(): permite crear una matriz identidad. Matriz con ceros en las filas y columnas excepto en la diagonal que tendremos unos.

iden2 = np.identity(4)

iden2  # Salida: array([[1., 0., 0., 0.],
       #                [0., 1., 0., 0.],
       #                [0., 0., 1., 0.],
       #                [0., 0., 0., 1.]])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# np.eye(): matriz identidad con la que podemos modificar la posición de la diagonal con el parámetro K

eye1 = np.eye(4)

eye1  # Salida: array([[1., 0., 0., 0.],
      #                [0., 1., 0., 0.],
      #                [0., 0., 1., 0.],
      #                [0., 0., 0., 1.]])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# Mover la diagonal una posición hacia arriba

eye2 = np.eye(4, k = 1)

eye2  # Salida: array([[0., 1., 0., 0.],
      #                [0., 0., 1., 0.],
      #                [0., 0., 0., 1.],
      #                [0., 0., 0., 0.]])

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [ ]:
# Mover la diagonal dos posiciones hacia arriba:

eye2 = np.eye(4, k = 2)

eye2  # Salida: array([[0., 0., 1., 0.],
      #                [0., 0., 0., 1.],
      #                [0., 0., 0., 0.],
      #                [0., 0., 0., 0.]])

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# Lo mismo para valores negativos:

eye2 = np.eye(4, k = -1)

eye2  # Salida: array([[0., 0., 0., 0.],
      #                [1., 0., 0., 0.],
      #                [0., 1., 0., 0.],
      #                [0., 0., 1., 0.]])

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
# np.random.randint(): nos devuelve números enteros aleatorios entre dos valores que le especifiquemos.

aleatoria = np.random.randint(0, 20, 8)  # Matriz unidimensional de 8 elementos aleatorios entre el 0 y el 20 (no incluido) 

aleatoria  # Salida: array([ 2, 14, 16,  2,  1,  2, 15, 17]

array([ 2, 14, 16,  2,  1,  2, 15, 17], dtype=int32)

In [ ]:
# Para generarar un array tridimensional de 2 matrices de 3 filas x 5 columnas con números aleatorios del 0-100 (no incluida)

aleatoria1 = np.random.randint(0, 100, (2, 3, 5))  # Primero rango de números, luego dimensiones del array

aleatoria1  # Salida: array([[[34,  5, 34, 56, 51],
            #                 [89, 69, 82, 58, 66],
            #                 [75, 41, 59, 68, 36]],

            #                [[28, 95, 91, 37, 59],
            #                 [46, 23, 41,  2,  8],
            #                 [92, 93, 89, 50, 97]]], dtype=int32)

array([[[34,  5, 34, 56, 51],
        [89, 69, 82, 58, 66],
        [75, 41, 59, 68, 36]],

       [[28, 95, 91, 37, 59],
        [46, 23, 41,  2,  8],
        [92, 93, 89, 50, 97]]], dtype=int32)

In [ ]:
# np.random.rand(): nos devuelve un array entre 0 - 1 (no incluido) con la forma que le especifiquemos. Los valores son float.

# Array tridimensional de 2 matrices con 3 filas x 5 columnas con números aleatorios del 0 - 1

aleatoria2 = np.random.rand(2, 3, 5)

aleatoria2  # Salida: array([[[0.30953931, 0.9984686 , 0.55819594, 0.12330322, 0.40067297],
            #                 [0.43237897, 0.78715817, 0.41008991, 0.87294752, 0.1283106 ],
            #                 [0.01018238, 0.01847217, 0.21904583, 0.76058512, 0.51913896]],

            #                [[0.14245593, 0.06229063, 0.69671923, 0.74791235, 0.48224743],
            #                 [0.39005976, 0.86032261, 0.11698124, 0.32595551, 0.78778918],
            #                 [0.88130086, 0.26734199, 0.02557209, 0.42728062, 0.14362044]]])

array([[[0.30953931, 0.9984686 , 0.55819594, 0.12330322, 0.40067297],
        [0.43237897, 0.78715817, 0.41008991, 0.87294752, 0.1283106 ],
        [0.01018238, 0.01847217, 0.21904583, 0.76058512, 0.51913896]],

       [[0.14245593, 0.06229063, 0.69671923, 0.74791235, 0.48224743],
        [0.39005976, 0.86032261, 0.11698124, 0.32595551, 0.78778918],
        [0.88130086, 0.26734199, 0.02557209, 0.42728062, 0.14362044]]])

In [ ]:
# np.random.random_sample(): nos devuelve un array entre 0 - 1 (no incluido) con la forma que le especifiquemos EN FORMA DE TUPLA. Los valores son float.

# Array tridimensional de 2 matrices con 3 filas x 5 columnas con números aleatorios del 0 - 1

aleatoria3 = np.random.random_sample((2, 3, 5))

aleatoria3  # Salida: array([[[0.53052643, 0.65093388, 0.83970651, 0.10842694, 0.15070011],
            #                 [0.23306723, 0.33917582, 0.62670284, 0.8010868 , 0.53002884],
            #                 [0.31641693, 0.24454779, 0.93503678, 0.09416233, 0.55316614]],

            #                [[0.90533076, 0.26195768, 0.73729793, 0.01036003, 0.18048762],
            #                 [0.38267311, 0.99318575, 0.46873725, 0.62115441, 0.43199547],
            #                 [0.75224802, 0.8322811 , 0.18743643, 0.67211054, 0.71001918]]])

array([[[0.53052643, 0.65093388, 0.83970651, 0.10842694, 0.15070011],
        [0.23306723, 0.33917582, 0.62670284, 0.8010868 , 0.53002884],
        [0.31641693, 0.24454779, 0.93503678, 0.09416233, 0.55316614]],

       [[0.90533076, 0.26195768, 0.73729793, 0.01036003, 0.18048762],
        [0.38267311, 0.99318575, 0.46873725, 0.62115441, 0.43199547],
        [0.75224802, 0.8322811 , 0.18743643, 0.67211054, 0.71001918]]])

In [22]:
# np.random.choice(): Devuelve un valor aleatoriamente cada vez que se ejecute entre los valores de un iterable, en este caso una lista.
valor_aleatorio = np.random.choice([1, 2, 3, 5, 6, 7])
print(valor_aleatorio)

3


In [ ]:
# np.random.choice(): con un array:

aleatoria20 = np.array([ 2, 14, 16,  2,  1,  2, 15, 17])
print(aleatoria20)

valor_aleatorio2 = np.random.choice(aleatoria20)
print(valor_aleatorio2)

[ 2 14 16  2  1  2 15 17]
16


# Propiedades

In [ ]:
# Crear un array de 2 filas x 3 columnas

ejemplo = np.random.random_sample((2,3))

ejemplo

array([[0.27494899, 0.15961992, 0.97530487],
       [0.85997389, 0.45447119, 0.4632279 ]])

# Métodos para comprender y explorar las propiedades de un array

In [ ]:
# type(): averiguar el tipo de dato

type(ejemplo)  # Salida: numpy.ndarray

numpy.ndarray

In [ ]:
# .ndim: nos permite conocer el número de dimensiones de nuestro array

ejemplo.ndim  # Salida: 2

2

In [ ]:
# .shape: nos permite conocer la forma del array

ejemplo.shape  # Salida: (2, 3)

(2, 3)

In [ ]:
# .dtype: obtenemos el tipo de dato que contiene nuestro array

ejemplo.dtype  # salida: dtype('float64')

dtype('float64')