In [ ]:
# import numpy as np
# print(np.__version__)

# Unidimensional

In [ ]:
# Sintaxis: Se realiza igual que en una lista

lista[start:stop:step]
'''
Donde:

start: es el primer elemento al que se quiere acceder, este elemento será incluido. 

stop: es el ultimo elemento al que se quiere acceder, este elemento no será incluido. 

step: es el intervalo con el que se tomaran los elementos.
'''

In [ ]:
# Repaso a las listas

lst = [12,20,3,45,6,23,81,93]

# Acceder al elemento de la posición 3
print(lst[3])  # Salida: 45

# Seleccionamos desde el tercer elemento (incluido) hasta el final
print(lst[2:])  # Salida: [3, 45, 6, 23, 81, 93]

# Seleccionamos desde el tercer elemento hasta el 5 incluido
print(lst[2:5])  # Salida: [3, 45, 6]

# Seleccionamos los 4 primeros elementos
print(lst[:4])  # Salida: [12, 20, 3, 45]

# Seleccionamos todos los elementos que están en posición impar
print(lst[::2])  # Salida: [12, 3, 6, 81]

45
[3, 45, 6, 23, 81, 93]
[3, 45, 6]
[12, 20, 3, 45]
[12, 3, 6, 81]


In [ ]:
# Array unidimensional de 15 elementos tipo float:

unidimensional = ([0.11004851, 0.04858927, 0.25918084, 0.98074997, 0.47281141,
                   0.06919704, 0.73482103, 0.67461802, 0.9731047 , 0.61204223,
                   0.64327416, 0.89920378, 0.25789705, 0.15254418, 0.64145759])

# Si queremos acceder al primer elemento de nuestro array
print(unidimensional[0])  # Salida: 0.11004851

# Si queremos acceder a los tres últimos elementos
print(unidimensional[-3:])  # Salida: [0.25789705, 0.15254418, 0.64145759]

# Si queremos seleccionar el tercer y cuarto elemento
print(unidimensional[2:4])  # Salida: [0.25918084, 0.98074997]

# Los elementos desde el inicio (1) hasta el 10 incluido (posición 9) en saltos de dos en dos
print(unidimensional[:10:2])  # Salida: [0.11004851, 0.25918084, 0.47281141, 0.73482103, 0.9731047]

0.11004851
[0.25789705, 0.15254418, 0.64145759]
[0.25918084, 0.98074997]
[0.11004851, 0.25918084, 0.47281141, 0.73482103, 0.9731047]


# Bidimensional

# Pueden entenderse como una lista de listas.

# Sintaxis, se pueden representar de dos formas:

array[i,j]    i: filas
array[i][j]  j: columnas

In [ ]:
# Array bidimensional de 20 elementos tipo float:

bidimensional = np.random.rand(5, 4)

bidimensional = array([[0.63499975, 0.27702147, 0.2867511 , 0.52455559],
                       [0.48413625, 0.68914156, 0.61253637, 0.5552737 ],
                       [0.72277012, 0.06624284, 0.72344753, 0.56445487],
                       [0.1919691 , 0.98874766, 0.09926572, 0.16397561],
                       [0.19056812, 0.56586721, 0.11789614, 0.41540677]])

In [55]:
# Accedemos a la fila 0
print(bidimensional[0])  # Salida: [0.63499975 0.27702147 0.2867511  0.52455559]

# Accedemos al elemento de la fila 0 columna 0
print(bidimensional[0,0])  # Salida: 0.6349997460948548

# Esto es lo mismo que lo anterior
print(bidimensional[0][0])  # Salida: 0.6349997460948548

# Segunda fila, tercer columna.
print(bidimensional[1, 2]) # Salida: 0.6125363703490366

# Cuando utilicemos la estructura bidimensional[0,0], todo lo que vaya antes de la coma se referirá a las filas. Y todo lo
# que vaya después se referirá a las columnas.

# Seleccionar solo las dos primeras filas:
print(bidimensional[:2, :])  # Salida: [[0.63499975 0.27702147 0.2867511  0.52455559]
                             #          [0.48413625 0.68914156 0.61253637 0.5552737 ]]

# Seleccionar el último elemento de la matriz, es decir, el cuarto elemento de la quinta fila:
print(bidimensional[-1, -1])

# Seleccionar el tercer elemento de la cuarta fila:
print(bidimensional[3:4, 2:3])

[0.63499975 0.27702147 0.2867511  0.52455559]
0.6349997460948548
0.6349997460948548
0.6125363703490366
[[0.63499975 0.27702147 0.2867511  0.52455559]
 [0.48413625 0.68914156 0.61253637 0.5552737 ]]
0.41540676607934846
[[0.09926572]]


In [ ]:
# Cambiar los valores de nuestro array que sean > 0,5 por -1

for filas in range(bidimensional.shape[0]):         # shape[0] = cantidad de filas → usas eso para recorrer el eje vertical
    for columnas in range(bidimensional.shape[1]):  # shape[1] = cantidad de columnas → usas eso para recorrer el eje horizontal
        if bidimensional[filas][columnas] > 0.5:
            bidimensional[filas][columnas] = -1

print(bidimensional)  # Salida: [[-1.          0.27702147  0.2867511  -1.        ]
                      #          [ 0.48413625 -1.         -1.         -1.        ]
                      #          [-1.          0.06624284 -1.         -1.        ]
                      #          [ 0.1919691  -1.          0.09926572  0.16397561]
                      #          [ 0.19056812 -1.          0.11789614  0.41540677]]
            

[[-1.          0.27702147  0.2867511  -1.        ]
 [ 0.48413625 -1.         -1.         -1.        ]
 [-1.          0.06624284 -1.         -1.        ]
 [ 0.1919691  -1.          0.09926572  0.16397561]
 [ 0.19056812 -1.          0.11789614  0.41540677]]


# Multidimensional

# Sintaxis, se pueden representar de dos formas:

array[i,j,k]     i : array al que queremos acceder
array[i][j][k]   j : fila de nuestro array al que queremos acceder
                 k : columna de nuestro array al que queremos acceder

In [ ]:
multidimensional = np.random.randint(0, 100, (2, 3, 5))

multidimensional = array([[[38, 75,  5, 35, 36],
                           [40, 74, 20, 67,  7],
                           [12, 44, 40, 67, 38]],

                          [[90, 59, 74, 23, 26],
                           [ 3, 51, 40, 36, 74],
                           [99, 33, 56, 81, 92]]], dtype=int32)

In [ ]:
# Accedemos al array 1 y al elemento que está en la fila 2 y la columna 4
print(multidimensional[0, 1, 3])  # Salida: 67
 
# Primer array primera fila y todas las columnas
print(multidimensional[0, 0, :])  # Salida: [38 75  5 35 36]

# Del primer array la primera columna de todas las filas
print(multidimensional[0, :, 0]) # Salida: [38 40 12]

# Nos devuelva las dos últimas filas del segundo array
print(multidimensional[1, 1:, :])  # Salida: [[ 3 51 40 36 74]
                                   #          [99 33 56 81 92]]

67
[38 75  5 35 36]
[38 40 12]
[[ 3 51 40 36 74]
 [99 33 56 81 92]]
